### ISSUE TITLE
Helps pls for Filter and merge 

### ISSUE THREAD

**Issue by wuilmerj24** [vettich/un-rethinkdb-rs#3]
Hi, how to make filter and merge. Exist any example?

**Comment by vettich** [comment]
Hi. You can look at the documentation for these methods, there are many examples there:
- [filter](https://docs.rs/unreql/latest/unreql/enum.Command.html#method.filter)
- [merge](https://docs.rs/unreql/latest/unreql/enum.Command.html#method.merge)
